[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "e2b>=2.46.4",
    "fastapi[standard]>=0.141.1",
    "google-genai>=1.0",
    "neatlogs[google-genai,langchain,openai]",
    "openai>=1.0",
    "pydantic-settings>=2.0",
]
